<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCzskifh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCzskifh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCzskifh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCzskifh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCzskifh\appDevDebugProjectContainer();
