<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOaq3r1m\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOaq3r1m/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOaq3r1m.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOaq3r1m\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOaq3r1m\appDevDebugProjectContainer();
