<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFycf9pl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFycf9pl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFycf9pl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFycf9pl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFycf9pl\appDevDebugProjectContainer();
